# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
  version: 3.8
  install:
    - requirements: docs/source/sphinx_requirements.txt

sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py
