#!/usr/bin/env python3

import subprocess
import os
import sys

build_tag = 'latest'
os.environ['BUILD_TAG'] = build_tag
args = ["docker-compose"] + sys.argv[1:]
subprocess.check_call(args, cwd="tests/integration")
