from logging import Filter, LogRecord
from typing import Any


class PrefixFilter(Filter):
    def __init__(self, prefix: str, separator: str = ...) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def filter(self, record: LogRecord) -> bool: ...
