from packaging.version import Version as Version
from typing import Any, Optional, TypeVar, Generic

TConfig = TypeVar('TConfig', bound=Any)


class Handler(Generic[TConfig]):
    DEFAULT_FILENAME: str = ...
    @staticmethod
    def empty() -> TConfig: ...
    @staticmethod
    def from_string(data: str) -> TConfig: ...
    @staticmethod
    def from_filename(filename: str) -> TConfig: ...
    @staticmethod
    def get_version(config: TConfig) -> Optional[Version]: ...
    @staticmethod
    def update_from_file(config: TConfig, filename: str) -> None: ...
