from .base import Handler as Handler
from configparser import ConfigParser
from packaging.version import Version
from typing import Optional


class IniHandler(Handler[ConfigParser]):
    DEFAULT_FILENAME: str = ...
    @staticmethod
    def empty() -> ConfigParser: ...
    @staticmethod
    def from_string(data: str) -> ConfigParser: ...
    @staticmethod
    def from_filename(filename: str) -> ConfigParser: ...
    @staticmethod
    def get_version(config: ConfigParser) -> Optional[Version]: ...
    @staticmethod
    def update_from_file(config: ConfigParser, filename: str) -> None: ...
